In [42]:
import json
import csv

with open(r'F:\lvcai\guangdong_round2_train_20181011\单瑕疵图片\不导电\不导电20180830131536对照样本.json',encoding='UTF-8') as f:
    jsonData=json.load(f)
    
print(jsonData['shapes'][0])
print(jsonData['shapes'][0]['label'])
print(jsonData['shapes'][0]['points'])

{'label': '不导电', 'line_color': None, 'points': [[0, 995], [2560, 995], [2560, 1409], [0, 1409]], 'fill_color': None}
不导电
[[0, 995], [2560, 995], [2560, 1409], [0, 1409]]


In [10]:
import os

base_dir='F:/lvcai/guangdong_round2_train_20181011/单瑕疵图片'

base_list=os.listdir(base_dir)

In [11]:
base_list

['不导电', '喷流', '擦花', '杂色', '桔皮', '漆泡', '漏底', '脏点', '角位漏底', '起坑']

In [14]:
sec_dir=[]
for b in base_list:
    sec_dir.append(base_dir+'/'+ str(b))

In [15]:
print(sec_dir)

['F:/lvcai/guangdong_round2_train_20181011/单瑕疵图片/不导电', 'F:/lvcai/guangdong_round2_train_20181011/单瑕疵图片/喷流', 'F:/lvcai/guangdong_round2_train_20181011/单瑕疵图片/擦花', 'F:/lvcai/guangdong_round2_train_20181011/单瑕疵图片/杂色', 'F:/lvcai/guangdong_round2_train_20181011/单瑕疵图片/桔皮', 'F:/lvcai/guangdong_round2_train_20181011/单瑕疵图片/漆泡', 'F:/lvcai/guangdong_round2_train_20181011/单瑕疵图片/漏底', 'F:/lvcai/guangdong_round2_train_20181011/单瑕疵图片/脏点', 'F:/lvcai/guangdong_round2_train_20181011/单瑕疵图片/角位漏底', 'F:/lvcai/guangdong_round2_train_20181011/单瑕疵图片/起坑']


In [16]:
sec_dir[0]

'F:/lvcai/guangdong_round2_train_20181011/单瑕疵图片/不导电'

In [44]:
sec_dir[0][9:]

'guangdong_round2_train_20181011/单瑕疵图片/不导电'

In [43]:
sample_list=os.listdir(sec_dir[0])

In [21]:
sample_list

['不导电20180830131536对照样本.jpg',
 '不导电20180830131536对照样本.json',
 '不导电20180830131551对照样本.jpg',
 '不导电20180830131551对照样本.json',
 '不导电20180830131628对照样本.jpg',
 '不导电20180830131628对照样本.json',
 '不导电20180830131827对照样本.jpg',
 '不导电20180830131827对照样本.json',
 '不导电20180830134330对照样本.jpg',
 '不导电20180830134330对照样本.json',
 '不导电20180830134402对照样本.jpg',
 '不导电20180830134402对照样本.json',
 '不导电20180830134743对照样本.jpg',
 '不导电20180830134743对照样本.json',
 '不导电20180830135013对照样本.jpg',
 '不导电20180830135013对照样本.json',
 '不导电20180830135838对照样本.jpg',
 '不导电20180830135838对照样本.json',
 '不导电20180830140724对照样本.jpg',
 '不导电20180830140724对照样本.json',
 '不导电20180830140809对照样本.jpg',
 '不导电20180830140809对照样本.json',
 '不导电20180830142508对照样本.jpg',
 '不导电20180830142508对照样本.json',
 '不导电20180830155325对照样本.jpg',
 '不导电20180830155325对照样本.json',
 '不导电20180831100602对照样本.jpg',
 '不导电20180831100602对照样本.json',
 '不导电20180831100625对照样本.jpg',
 '不导电20180831100625对照样本.json',
 '不导电20180831101421对照样本.jpg',
 '不导电20180831101421对照样本.json',
 '不导电20180831101630对照样本.

In [34]:
sample_list[1][-4:]

'json'

In [48]:
points_list=jsonData['shapes'][0]['points']

In [49]:
import numpy as np
points_array=np.array(points_list)

In [50]:
points_array

array([[   0,  995],
       [2560,  995],
       [2560, 1409],
       [   0, 1409]])

In [52]:
type(points_array[0])

numpy.ndarray

In [53]:
points_array[0][0]

0

In [54]:
points_array[0][1]

995

In [63]:
points_array[0:4,0:2]

array([[   0,  995],
       [2560,  995],
       [2560, 1409],
       [   0, 1409]])

In [64]:
points_array[:,0]

array([   0, 2560, 2560,    0])

In [67]:
points_array[:,1]

array([ 995,  995, 1409, 1409])

In [68]:
np.max(points_array[:,0])

2560

In [70]:
np.min(points_array[:,0])

0

In [69]:
np.max(points_array[:,1])

1409

In [71]:
np.min(points_array[:,1])

995

In [72]:
import numpy as np

def deal_points(points_list):
    #points_list = [[0, 995], [2560, 995], [2560, 1409], [0, 1409]]
    points_array=np.array(points_list)
    x=np.min(points_array[:,0])
    y=np.min(points_array[:,1])
    
    w=np.max(points_array[:,0])-x
    h=np.max(points_array[:,1])-y
    
    return x,y,w,h

In [77]:
json_list=[]

for i in sample_list:
    if i[-4:]=='json':
        file_name=sec_dir[0]+'/'+i
        with open(file_name,encoding='UTF-8') as f:
            jsonData=json.load(f)
    
        print(jsonData['shapes'][0])  
        label="defect0"
        x,y,w,h=deal_points(jsonData['shapes'][0]['points'])
        
        json_list.append({'file_name':file_name[9:],'label':label,'x':x,'y':y,'w':w,'h':h})

{'label': '不导电', 'line_color': None, 'points': [[0, 995], [2560, 995], [2560, 1409], [0, 1409]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 1036], [2560, 1036], [2560, 1483], [0, 1483]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 979], [2560, 979], [2560, 1405], [0, 1405]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 121], [2557, 121], [2557, 702], [0, 702]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[961, 463], [2136, 463], [2136, 734], [961, 734]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[728, 314], [963, 314], [963, 610], [728, 610]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[536, 0], [842, 0], [842, 326], [536, 326]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 754], [2560, 754], [2560, 1391], [0, 1391]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 760], [2560, 7

{'label': '不导电', 'line_color': None, 'points': [[22, 1393], [2560, 1393], [2560, 1517], [22, 1517]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[24, 1624], [811, 1624], [811, 1791], [24, 1791]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[748, 1307], [1605, 1307], [1605, 1475], [748, 1475]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 1185], [2560, 1185], [2560, 1297], [0, 1297]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[187, 1001], [2560, 1001], [2560, 1136], [187, 1136]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[493, 932], [1175, 932], [1175, 995], [493, 995]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 940], [2560, 940], [2560, 1375], [0, 1375]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 1048], [2560, 1048], [2560, 1379], [0, 1379]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'po

{'label': '不导电', 'line_color': None, 'points': [[2428, 1060], [2560, 1060], [2560, 1248], [2428, 1248]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 746], [2560, 746], [2560, 973], [0, 973]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 758], [2560, 758], [2560, 999], [0, 999]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 593], [2560, 593], [2560, 871], [0, 871]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 662], [2560, 662], [2560, 952], [0, 952]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 805], [2560, 805], [2560, 1097], [0, 1097]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 769], [2560, 769], [2560, 995], [0, 995]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[556, 787], [1220, 787], [1220, 1173], [556, 1173]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 597], [256

{'label': '不导电', 'line_color': None, 'points': [[0, 714], [2560, 714], [2560, 1205], [0, 1205]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 687], [2560, 687], [2560, 1164], [0, 1164]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 514], [2560, 514], [2560, 993], [0, 993]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 758], [2560, 758], [2560, 1222], [0, 1222]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[282, 449], [438, 449], [438, 761], [282, 761]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[929, 684], [1173, 684], [1173, 981], [929, 981]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[152, 714], [390, 714], [390, 919], [152, 919]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 1019], [2560, 1019], [2560, 1119], [0, 1119]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 1011], [25

{'label': '不导电', 'line_color': None, 'points': [[0, 684], [2560, 684], [2560, 1078], [0, 1078]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 690], [2560, 690], [2560, 1098], [0, 1098]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[5, 711], [2560, 711], [2560, 1130], [5, 1130]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[5, 619], [2560, 619], [2560, 961], [5, 961]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 440], [2560, 440], [2560, 841], [0, 841]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 696], [2560, 696], [2560, 1131], [0, 1131]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 455], [2560, 455], [2560, 937], [0, 937]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[0, 687], [2560, 687], [2560, 1146], [0, 1146]], 'fill_color': None}
{'label': '不导电', 'line_color': None, 'points': [[2, 558], [2560, 558],

In [78]:
json_list

[{'file_name': 'guangdong_round2_train_20181011/单瑕疵图片/不导电/不导电20180830131536对照样本.json',
  'h': 414,
  'label': 'defect0',
  'w': 2560,
  'x': 0,
  'y': 995},
 {'file_name': 'guangdong_round2_train_20181011/单瑕疵图片/不导电/不导电20180830131551对照样本.json',
  'h': 447,
  'label': 'defect0',
  'w': 2560,
  'x': 0,
  'y': 1036},
 {'file_name': 'guangdong_round2_train_20181011/单瑕疵图片/不导电/不导电20180830131628对照样本.json',
  'h': 426,
  'label': 'defect0',
  'w': 2560,
  'x': 0,
  'y': 979},
 {'file_name': 'guangdong_round2_train_20181011/单瑕疵图片/不导电/不导电20180830131827对照样本.json',
  'h': 581,
  'label': 'defect0',
  'w': 2557,
  'x': 0,
  'y': 121},
 {'file_name': 'guangdong_round2_train_20181011/单瑕疵图片/不导电/不导电20180830134330对照样本.json',
  'h': 271,
  'label': 'defect0',
  'w': 1175,
  'x': 961,
  'y': 463},
 {'file_name': 'guangdong_round2_train_20181011/单瑕疵图片/不导电/不导电20180830134402对照样本.json',
  'h': 296,
  'label': 'defect0',
  'w': 235,
  'x': 728,
  'y': 314},
 {'file_name': 'guangdong_round2_train_20181011/单瑕疵图片/

In [81]:
import pandas as pd
df= pd.DataFrame(json_list,columns=["file_name","label","x","y","w","h"])
df.to_csv("json_test.csv",index=False, encoding="utf-8")

In [82]:
name='F:\lvcai\guangdong_round2_train_20181011\单瑕疵图片\不导电\不导电20180830131536对照样本.json'

In [87]:
name[41:-4]

'单瑕疵图片\\不导电\\不导电20180830131536对照样本.'

In [89]:
test_list=[]
test_list.append({'file_name': 'guangdong_round2_train_20181011/单瑕疵图片/不导电/不导电20180831101841对照样本.json',
  'h': 325,
  'label': 'defect0',
  'w': 2560,
  'x': 0,
  'y': 1115})
test_list.append( {'file_name': '多瑕疵图片/不导电脏点20180921085423对照样本.jpg',
  'h': 47,
  'label': 9,
  'w': 30,
  'x': 0,
  'y': 1022})
df= pd.DataFrame(test_list,columns=["file_name","label","x","y","w","h"])
df.to_csv("yihao_test.csv",index=False, encoding="utf-8")

In [90]:
df1=pd.read_csv('json_dan.csv')
df2=pd.read_csv('json_duo.csv')

In [91]:
df1

file_name  label    x     y     w    h
0     单瑕疵图片/不导电/不导电20180830131536对照样本.jpg      0    0   995  2560  414
1     单瑕疵图片/不导电/不导电20180830131551对照样本.jpg      0    0  1036  2560  447
2     单瑕疵图片/不导电/不导电20180830131628对照样本.jpg      0    0   979  2560  426
3     单瑕疵图片/不导电/不导电20180830131827对照样本.jpg      0    0   121  2557  581
4     单瑕疵图片/不导电/不导电20180830134330对照样本.jpg      0  961   463  1175  271
5     单瑕疵图片/不导电/不导电20180830134402对照样本.jpg      0  728   314   235  296
6     单瑕疵图片/不导电/不导电20180830134743对照样本.jpg      0  536     0   306  326
7     单瑕疵图片/不导电/不导电20180830135013对照样本.jpg      0    0   754  2560  637
8     单瑕疵图片/不导电/不导电20180830135838对照样本.jpg      0    0   760  2560  435
9     单瑕疵图片/不导电/不导电20180830140724对照样本.jpg      0  146   169   763  320
10    单瑕疵图片/不导电/不导电20180830140809对照样本.jpg      0  536   376   333  282
11    单瑕疵图片/不导电/不导电20180830142508对照样本.jpg      0    0   517  2560  182
12    单瑕疵图片/不导电/不导电20180830155325对照样本.jpg      0    0  1230  2560  379
13    单瑕疵图片/不导电/不导电20180831100602对照样本.jpg      0    0  1281  2560  377
14    单瑕疵图片/不导电/不导电20180831100625对照样本.jpg      0    0  1297  2560  394
15    单瑕疵图片/不导电/不导电20180831101421对照样本.jpg      0    0   977  2560  426
16    单瑕疵图片/不导电/不导电20180831101630对照样本.jpg      0    0   973  2560  383
17    单瑕疵图片/不导电/不导电20180831101642对照样本.jpg      0    0  1103  2560  343
18    单瑕疵图片/不导电/不导电20180831101753对照样本.jpg      0    0  1331  2560  327
19    单瑕疵图片/不导电/不导电20180831101841对照样本.jpg      0    0  1115  2560  325
20    单瑕疵图片/不导电/不导电20180831102055对照样本.jpg      0    0   707  2560  665
21    单瑕疵图片/不导电/不导电20180831102726对照样本.jpg      0    0   658  2560  929
22    单瑕疵图片/不导电/不导电20180831102759对照样本.jpg      0    0   858  2560  937
23    单瑕疵图片/不导电/不导电20180831102813对照样本.jpg      0    0   981  2560  936
24    单瑕疵图片/不导电/不导电20180831102827对照样本.jpg      0    0  1146  2560  774
25    单瑕疵图片/不导电/不导电20180831102843对照样本.jpg      0    0   824  2560  887
26    单瑕疵图片/不导电/不导电20180831102911对照样本.jpg      0    0   940  2560  902
27    单瑕疵图片/不导电/不导电20180831102927对照样本.jpg      0    0   862  2560  884
28    单瑕疵图片/不导电/不导电20180831102939对照样本.jpg      0    0   977  2560  889
29    单瑕疵图片/不导电/不导电20180831103739对照样本.jpg      0    0  1128  2560  722
...                                   ...    ...  ...   ...   ...  ...
2746    单瑕疵图片/起坑/起坑20180929112130对照样本.jpg      7    0  1075  2560  216
2747    单瑕疵图片/起坑/起坑20180929113243对照样本.jpg      7    0   753  2560  105
2748    单瑕疵图片/起坑/起坑20180929113326对照样本.jpg      7    0   793  2560  106
2749    单瑕疵图片/起坑/起坑20180929113333对照样本.jpg      7    0   720  2560  102
2750    单瑕疵图片/起坑/起坑20180929113355对照样本.jpg      7    0   870  2560  113
2751    单瑕疵图片/起坑/起坑20180929113453对照样本.jpg      7    0   872  2560  110
2752    单瑕疵图片/起坑/起坑20180929113556对照样本.jpg      7    0   457  2560   87
2753    单瑕疵图片/起坑/起坑20180929113606对照样本.jpg      7    0   793  2560   94
2754    单瑕疵图片/起坑/起坑20180929113620对照样本.jpg      7    0   779  2560   75
2755    单瑕疵图片/起坑/起坑20180929113625对照样本.jpg      7    0   815  2560   65
2756    单瑕疵图片/起坑/起坑20180929113656对照样本.jpg      7    0   750  2560   47
2757    单瑕疵图片/起坑/起坑20180929113720对照样本.jpg      7    0   915  2560   43
2758    单瑕疵图片/起坑/起坑20180929113851对照样本.jpg      7    0  1454  2560   64
2759    单瑕疵图片/起坑/起坑20180929113856对照样本.jpg      7    0  1003  2560   43
2760    单瑕疵图片/起坑/起坑20180929113903对照样本.jpg      7    0  1105  2560   47
2761    单瑕疵图片/起坑/起坑20180929114025对照样本.jpg      7    0   858  2560  100
2762    单瑕疵图片/起坑/起坑20180929114032对照样本.jpg      7    0   822  2560   89
2763    单瑕疵图片/起坑/起坑20180929114052对照样本.jpg      7    0   774  2560   85
2764    单瑕疵图片/起坑/起坑20180929114104对照样本.jpg      7    0   617  2560   80
2765    单瑕疵图片/起坑/起坑20180929114116对照样本.jpg      7    0   613  2560   70
2766    单瑕疵图片/起坑/起坑20180929114147对照样本.jpg      7    0   930  2560   94
2767    单瑕疵图片/起坑/起坑20180929114157对照样本.jpg      7    0   638  2560   71
2768    单瑕疵图片/起坑/起坑20180929114836对照样本.jpg      7    0   824  2560   81
2769    单瑕疵图片/起坑/起坑20180929115001对照样本.jpg      7    0   852  2560   61
2770    单瑕疵图片/起坑/起坑20180929115023对照样本.jpg      7    0   

In [92]:
df2

file_name  label     x     y     w    h
0    多瑕疵图片/不导电,脏点20180921085423对照样本.jpg      0   956  1028   353   49
1    多瑕疵图片/不导电,脏点20180921085423对照样本.jpg      9  1046   960    57   43
2    多瑕疵图片/不导电,脏点20180921085423对照样本.jpg      9     0  1022    30   47
3    多瑕疵图片/不导电,脏点20180921085423对照样本.jpg      9  2320  1177    34   34
4    多瑕疵图片/不导电,脏点20180921085507对照样本.jpg      0     0   948   738  453
5    多瑕疵图片/不导电,脏点20180921085507对照样本.jpg      9  2352  1209   102   94
6    多瑕疵图片/不导电,脏点20180921085557对照样本.jpg      0     9   975  2551  469
7    多瑕疵图片/不导电,脏点20180921085557对照样本.jpg      9  1903  1107    29   41
8    多瑕疵图片/不导电,脏点20180921085557对照样本.jpg      9  1240  1013    43   31
9    多瑕疵图片/不导电,脏点20180921085557对照样本.jpg      9  1271  1201   214   45
10   多瑕疵图片/不导电,脏点20180921091747对照样本.jpg      0     0  1113   552  225
11   多瑕疵图片/不导电,脏点20180921091747对照样本.jpg      9  1252  1254    64   41
12   多瑕疵图片/不导电,脏点20180921091747对照样本.jpg      9   899   891    64   47
13   多瑕疵图片/不导电,脏点20180921091747对照样本.jpg      9   458   889    43   28
14   多瑕疵图片/不导电,脏点20180921093046对照样本.jpg      9   611  1442    35   45
15   多瑕疵图片/不导电,脏点20180921093046对照样本.jpg      9    63  1258   114   72
16   多瑕疵图片/不导电,脏点20180921093046对照样本.jpg      9  1299  1083    49   41
17   多瑕疵图片/不导电,脏点20180921093046对照样本.jpg      0  1611  1038   539   55
18   多瑕疵图片/不导电,脏点20180921093508对照样本.jpg      9  2516  1232    24   47
19   多瑕疵图片/不导电,脏点20180921093508对照样本.jpg      9  1165  1350    55   47
20   多瑕疵图片/不导电,脏点20180921093508对照样本.jpg      0     0  1144  2560   39
21   多瑕疵图片/不导电,脏点20180921105408对照样本.jpg      9   473  1424    45   38
22   多瑕疵图片/不导电,脏点20180921105408对照样本.jpg      0     0  1491  2560   80
23   多瑕疵图片/不导电,脏点20180921105418对照样本.jpg      0     0  1554  2560  104
24   多瑕疵图片/不导电,脏点20180921105418对照样本.jpg      9  2465  1456    53   43
25   多瑕疵图片/不导电,脏点20180921153903对照样本.jpg      0    89  1544  1737  114
26   多瑕疵图片/不导电,脏点20180921153903对照样本.jpg      9     1   746  1245  492
27   多瑕疵图片/不导电,脏点20180921155221对照样本.jpg      0   618  1711  1936  151
28   多瑕疵图片/不导电,脏点20180921155221对照样本.jpg      9   991  1232    86   59
29   多瑕疵图片/不导电,脏点20180921155221对照样本.jpg      9  1528  1507    53   45
..                                  ...    ...   ...   ...   ...  ...
628   多瑕疵图片/起坑,脏点20180928192612对照样本.jpg      9  1787   587   312   63
629   多瑕疵图片/起坑,脏点20180928192638对照样本.jpg      7     0   844  2560  141
630   多瑕疵图片/起坑,脏点20180928192638对照样本.jpg      9     7   715   580  129
631   多瑕疵图片/起坑,脏点20180928192638对照样本.jpg      9   126   936   320  169
632   多瑕疵图片/起坑,脏点20180929110931对照样本.jpg      7     0  1048  2560  135
633   多瑕疵图片/起坑,脏点20180929110931对照样本.jpg      9   291  1338    69   41
634   多瑕疵图片/起坑,脏点20180929110943对照样本.jpg      7     0   938  2560  112
635   多瑕疵图片/起坑,脏点20180929110943对照样本.jpg      9  1699   920    57   40
636   多瑕疵图片/起坑,脏点20180929110943对照样本.jpg      9  1532   715    55   39
637   多瑕疵图片/起坑,脏点20180929111014对照样本.jpg      7     0   828  2560  110
638   多瑕疵图片/起坑,脏点20180929111014对照样本.jpg      9  1226   869    32   30
639   多瑕疵图片/起坑,脏点20180929111024对照样本.jpg      9  1301   569    55   38
640   多瑕疵图片/起坑,脏点20180929111024对照样本.jpg      9  1765  1066    51   47
641   多瑕疵图片/起坑,脏点20180929111024对照样本.jpg      7     0   809  2560  104
642   多瑕疵图片/起坑,脏点20180929111044对照样本.jpg      9  1342   789    94   88
643   多瑕疵图片/起坑,脏点20180929111044对照样本.jpg      7     0   964  2560  123
644   多瑕疵图片/起坑,脏点20180929113708对照样本.jpg      9   554   903    41   29
645   多瑕疵图片/起坑,脏点20180929113708对照样本.jpg      7     0   875  2560   38
646   多瑕疵图片/起坑,脏点20180929113708对照样本.jpg      9  2452   562    55   53
647   多瑕疵图片/起坑,脏点20180929114057对照样本.jpg      7     0   946  2560   90
648   多瑕疵图片/起坑,脏点20180929114057对照样本.jpg      9   114   903    49   47
649   多瑕疵图片/起坑,脏点20180929114928对照样本.jpg      7     0  1038  2560   71
650   多瑕疵图片/起坑,脏点20180929114928对照样本.jpg      9  1181  1297    63   45
651   多瑕疵图片/起坑,脏点20180929114934对照样本.jpg      9    54  1136    57   73
652   多瑕疵图片/起坑,脏点20180929114934对照样本.jpg      7     0   862  2560   76
653   多瑕疵图片/起坑,脏点20180929114943对照样本.jpg 